### ISSUE TITLE
Load vicuna weights

### ISSUE THREAD

**Issue by WeitaiKang** [Chat-3D/Chat-3D-v2#10]
<img width="1524" alt="image" src="https://github.com/Chat-3D/Chat-3D-v2/assets/123266287/cc751e72-8b4d-4745-bdb5-ceec90152544">

Dear authors, i found that there's a warning indicating the weights of my vicuna model miss some parameters.

I actually first download the llama from https://github.com/shawwn/llama-dl, then i convert it to HF by https://huggingface.co/docs/transformers/main/model_doc/llama, then i use your model/apply_delta.py to comply the llama to vicuna.

It seems that everything is smooth except for that i download the llama from shawwn not official.

So is this missing weight warning normal? or would you mind sharing your vicuna?

**Comment by WeitaiKang** [comment]
<img width="985" alt="image" src="https://github.com/Chat-3D/Chat-3D-v2/assets/123266287/8a326444-28ac-4663-8d2f-3c32983d864d">

I found those parameters are not learnable, so i guess it would be fine. Nothing wrong. Right?

**Comment by ZzZZCHS** [comment]
It's OK. I think I got the same warnings as yours.

**Comment by iris0329** [comment]
hi @WeitaiKang , How about your experiment with this unofficial llama ckpt? is everything goes well? 
I did not get the official reply from llama, seems to be ghosted.
