### ISSUE TITLE
Ask for PointGroup results

### ISSUE THREAD

**Issue by WeitaiKang** [Chat-3D/Chat-3D-v2#11]
Dear authors, 

Thanks for your great job! I now want to do some tiny modification which relies on the PointGroup segmentation results. However, the attributes files only contain the bbox results. Therefore, i wonder if you can provide the segmentation results with the semantic classification of the raw 607 types.

**Comment by ZzZZCHS** [comment]
You can download the segmentation results provided by [InstanceRefer](https://github.com/CurryYuan/InstanceRefer?tab=readme-ov-file#data-preparation) (Data preparation - Step 4) as we did.

**Comment by WeitaiKang** [comment]
Great! Thanks for your prompt!
