### ISSUE TITLE
Ask for visualization

### ISSUE THREAD

**Issue by WeitaiKang** [Chat-3D/Chat-3D-v2#12]
Dear authors, 

Thanks for you great job! Would you mind sharing your code of how to visualize those figures in your paper?

**Comment by ZzZZCHS** [comment]
For the bounding boxes, you can refer to [ground_visualize.py](https://github.com/Chat-3D/Chat-3D-v2/blob/main/others/ground_visualize.py).

For the object labels, they were manually attached to the pictures.

**Comment by WeitaiKang** [comment]
Great! Thank you very much!
