### ISSUE TITLE
ScanQA finetuning

### ISSUE THREAD

**Issue by cy94** [Chat-3D/Chat-3D-v2#13]
Hi @ZzZZCHS, thanks for releasing the code :) Could you please provide the instructions to finetune and evaluate on ScanQA?

**Comment by ZzZZCHS** [comment]
Hi, thanks for your interest. We are planning to release it in the next version of the code.

**Comment by ZzZZCHS** [comment]
Hi @cy94, we've recently released the refined implementation of Chat-3D v2, including the finetuning/evaluating code for ScanRefer, ScanQA, Scan2Cap, SQA3D, and Multi3DRefer. Also, we release the preprocessing code for all the annotations and extracted features. If you have any further questions, welcome to reopen the issue~
