### ISSUE TITLE
About the Identifier-rich Scene Captioning Dataset

### ISSUE THREAD

**Issue by ZCMax** [Chat-3D/Chat-3D-v2#15]
Thanks for your great work for the 3D-LLM domain, I‘ve checked the annotations provided in the google drive. However, I can not find the dentifier-rich Scene Captioning Dataset mentioned in the paper, would it be possible to provide this annotation file?

**Comment by ZzZZCHS** [comment]
I've uploaded it to the [Google Drive](https://drive.google.com/drive/folders/1S2R_gYaIrpzR8XuMeu-2igDzgAn98jH5?usp=drive_link) now. You can check it out. But actually the quality of this dataset is not very good. We are working on a more solid pipeline to generate scene captions.

**Comment by ZCMax** [comment]
Thanks!
