### ISSUE TITLE
object id

### ISSUE THREAD

**Issue by kuaileqipaoshui** [Chat-3D/Chat-3D-v2#16]

**Comment by kuaileqipaoshui** [comment]
How do I match an object to an id?  The object in the scene is asked by its id, but how can I match the id in the qa pairs with the object id If I get the original scene?

**Comment by ZzZZCHS** [comment]
The object instances are extracted by an object detector / segmentor. Then we assign each extracted object with a unique id. The information of each object (location, class name...) is saved in files like `scannet_train_attributes.pt`.
