### ISSUE TITLE
ModuleNotFoundError: No module named 'data' ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by Chunmian-art** [Chat-3D/Chat-3D-v2#17]
Hello, I meet the following missing ackages when I use extract_3dfeat.py.

Can you fix this bug?

Thank you.

**Comment by ZzZZCHS** [comment]
The `extract_3dfeat.py` is based on ULIP codes. So you need to include necessary packages from their [repo](https://github.com/salesforce/ULIP).
