### ISSUE TITLE
about parameters

### ISSUE THREAD

**Issue by iris0329** [Chat-3D/Chat-3D-v2#19]
Hi, I found in the code that the LLAMA model will be frozen, but it still needs over 24 GB of memory to train, except for the first stage.

Which part is the most computationally expensive?

I would appreciate a lot for your reply.

**Comment by ZzZZCHS** [comment]
Hi, sorry for the late reply. We hadn't figured out the reason until recently.

Firstly, our input for each object is "objxx: <object-level token> <scene-level>", which takes 6~7 tokens for each object. So, the input token length could sometimes reach 1000+ (for big scenes with 100+ objects), leading to extremely high costs at the attention layers in LLaMA. This can be reduced by limiting the max input token length and refining the object representation method. We are still working on it.

Another solution you can try right now is to use checkpoints in LLaMA. We add `self.llama_model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": False})` after loading LLaMA, and this can reduce memory cost to nearly 1/3 of the original one. I highly recommend trying this.

**Comment by ZzZZCHS** [comment]
Hi, @iris0329, we've recently released the refined implementation of Chat-3D v2, which solves the memory problem. If you have any further questions, welcome to reopen the issue~
