### ISSUE TITLE
CMT module

### ISSUE THREAD

**Issue by DevXiaoYan** [Chat-3D/Chat-3D-v2#2]
Thanks for Posting such interesting work. However, in the inference phase, the message in the chat3d.py file is that there is no CMT module, how to solve it?

**Comment by ZzZZCHS** [comment]
Hi, sorry for the inconvenience. The CMT module was missing when I initially uploaded the code. I have now updated the `models/` directory. Please check to see if it is working now.

**Comment by DevXiaoYan** [comment]
thank you very mach.
