### ISSUE TITLE
ImportError: FlashAttention2 has been toggled on

### ISSUE THREAD

**Issue by hanxunyu** [Chat-3D/Chat-3D-v2#21]
Thanks for your great work. But when I run run.sh, I met the error "ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error:the package flash_attn seems to be not installed." as shown in the following image.
![image](https://github.com/Chat-3D/Chat-3D-v2/assets/64463353/4f550d77-2884-4624-ba13-a923c04ce2ed)

And when I try "pip install flash_attn", the following error appears as shown in the second image.
Does anybody know how to fix it? Thanks very much.
![image](https://github.com/Chat-3D/Chat-3D-v2/assets/64463353/caf68e8b-69b3-40e8-af60-59897cb255b3)

**Comment by ZzZZCHS** [comment]
It seems that you are working with the [dev](https://github.com/Chat-3D/Chat-3D-v2/tree/dev) branch, which is currently 
 not ready for use. Please switch to the [main](https://github.com/Chat-3D/Chat-3D-v2/tree/main) branch instead.

**Comment by hanxunyu** [comment]
Thanks a lot.
