### ISSUE TITLE
Ask for extracting input for 3D encoder

### ISSUE THREAD

**Issue by jkstyle2** [Chat-3D/Chat-3D-v2#25]
Thanks for sharing your great work! It is very inspiring.

I have a few questions regarding 3D features for 3D encoder as input.

Firstly, would you mind telling why you chose 3D segmentation features as input for the 3D encoder?
I am looking for a research to utilize 3D features from 3D box detector, rather than 3D sementation, for multi-modal fusion with LLM.
I wonder if your Chat-3D-v2 can substitute 3D sementation features to 3D box features (such as VoteNet-family detector).

Secondly, is your benchmark result conducted on the instance annotation of ground truth or predicted segmentation result from PointGroup.

Thirdly, could you explain what does '# 3D data for alignment' mean in Table2 of your paper. 
It is said that the alignment is less applied compared to 3D-LLM, but it is not clear for me what exactly 'alignment' mean in this context.

Looking forward to your reply! 
Thanks.

**Comment by ZzZZCHS** [comment]
1. Yes, you can use 3D box detector instead of 3D instance segmentor. Both of them can acquire each instance's bbox and features.
2. The results are conducted on the predicted instance segmentation from PointGroup.
3. It means the alignment between feature space of 3D encoder and the embedding space of LLM / VLM. Basically, our data are all originated from ScanRefer (about 38K), while 3D-LLM uses more extra data such as Objaverse.

**Comment by jkstyle2** [comment]
Thanks for the considerate reply!
In the paper, it referred to supplementary materials, but I couldn't find any documment. Did you not publish it yet?

Also, regarding the gpu machine, is it possible to inference your model on 3090ti(24GB Mem) ?

**Comment by ZzZZCHS** [comment]
Sorry for the confusion. We haven't published the supplementary materials.

I'm afraid not. It takes 25~30 GB to inference with batch_size = 1. But if only for inference, maybe you can manually move part of model from GPU to CPU to lower the GPU usage.

**Comment by hanxunyu** [comment]
> Sorry for the confusion. We haven't published the supplementary materials.
> 
> I'm afraid not. It takes 25~30 GB to inference with batch_size = 1. But if only for inference, maybe you can manually move part of model from GPU to CPU to lower the GPU usage.

Thanks for your great work and do you have any plans to public the supplemental material?

**Comment by ZzZZCHS** [comment]
We have a plan to update the paper (with the supplementary materials).

**Comment by jkstyle2** [comment]
@ZzZZCHS, I'm trying to do the demo for inference on ScanRefer, as guided in README.
I setup the preprocessing step with instances from G.T and also ULIP-2 features (as instance from PointGroup and features from Uni-3D are not appeared).
However in your guide for the inference, it is required to modify config.py as to :
> val_file_s2=[
>   [
>     "annotations/scannet_pointgroup_uni3d_feats.pt",
>     "annotations/scannet_pointgroup_val_attributes.pt",
>     "annotations/scanrefer_pointgroup_val_stage2_grounding.json"
>   ]
> ]

It seems that the setting is for pointgroup and uni3d. Is this intended or should I make any modification?
Please tell us how to correctly follow the inference script.

Thanks for your help in advance!

**Comment by ZzZZCHS** [comment]
This config is correct. We use pointgroup segmented instances instead of GT instances during inference. Because we should suppose we do not have access to GT labels during inference. So you can directly follow the inference guide and everything should work fine.
