### ISSUE TITLE
Error when installing the requirements.txt for the newest version.

### ISSUE THREAD

**Issue by hanxunyu** [Chat-3D/Chat-3D-v2#30]
Thanks for your great work first. But when I prepare the environment for the newest version and I run `pip install -r requirements.txt`, I got the following error:
![image](https://github.com/Chat-3D/Chat-3D-v2/assets/64463353/53f72048-fcc1-45b3-a131-f9be756dbc23)
I guess maybe this error is related to the version of `setuptools` or `pip`, I have updated both to the newest version but it still failed. So could you please tell me what's the version of both you use? Or do anybody know how to fix this error? Thanks a lot.

**Comment by ZzZZCHS** [comment]
The error says: "ModuleNotFoundError: No module named 'packaging'". Could you try: `pip install packaging`

**Comment by hanxunyu** [comment]
Thanks for your quick relpy and I solved this problem. But when I run `bash scripts/run.sh` for training or inference, I got the following error:
![1714051044536](https://github.com/Chat-3D/Chat-3D-v2/assets/64463353/9f16e92a-69b6-4c51-96d7-e2c89503a09d)
Do you know how to fix this problem? Thanks a lot.

**Comment by hanxunyu** [comment]
Thanks for your reply and I have tried the newest code. But I got this error:
![aabe84017b1b4559e1b633c10138b8b](https://github.com/Chat-3D/Chat-3D-v2/assets/64463353/a511559b-ac3d-4172-9016-8998708d0077)
So I change `evaluate all(model, val loaders, start epoch-1. alobal step, device, config)` to `evaluate_all(model, model_without_ddp, val_loaders, start_epoch - 1, global_step, device, config)`. But then I got this error:
![image](https://github.com/Chat-3D/Chat-3D-v2/assets/64463353/afd367b1-a06d-4a91-af1e-3b891c61b726)
Do you know how to fix it?

**Comment by hanxunyu** [comment]
Otherwise, I see when run the inference phrase, this python file [helper](https://github.com/Chat-3D/Chat-3D-v2/blob/main/utils/helper.py) is needed. But the _annotations_ you provided not contain these two files:
![image](https://github.com/Chat-3D/Chat-3D-v2/assets/64463353/d5f8e0f4-6100-4921-881d-9dbba9347fe7)
 So I added them to the _annotation_ directory, is that right? Thanks again.

**Comment by ZzZZCHS** [comment]
> Thanks for your reply and I have tried the newest code. But I got this error: ![aabe84017b1b4559e1b633c10138b8b](https://private-user-images.githubusercontent.com/64463353/325901711-a511559b-ac3d-4172-9016-8998708d0077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjQ3NDcsIm5iZiI6MTcxNDEyNDQ0NywicGF0aCI6Ii82NDQ2MzM1My8zMjU5MDE3MTEtYTUxMTU1OWItYWMzZC00MTcyLTkwMTYtODk5ODcwOGQwMDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA5NDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViOTVjYmIzNDg1MTUyMWMxNmY4Y2Y3YTY5M2RkNDkzYzhjM2U1NDdmNDNkY2QwMTg2NWQ1NWEwMGQxZmZkM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uspwxBwTI8O4tImbl1oRggcTQoBG45YY8tuYjONhcH0) So I change `evaluate all(model, val loaders, start epoch-1. alobal step, device, config)` to `evaluate_all(model, model_without_ddp, val_loaders, start_epoch - 1, global_step, device, config)`. But then I got this error: ![image](https://private-user-images.githubusercontent.com/64463353/325904000-95d74951-2944-4f6c-af2d-f896baf9e008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjQ3NDcsIm5iZiI6MTcxNDEyNDQ0NywicGF0aCI6Ii82NDQ2MzM1My8zMjU5MDQwMDAtOTVkNzQ5NTEtMjk0NC00ZjZjLWFmMmQtZjg5NmJhZjllMDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA5NDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ODlkMGM0YTNhNmIwOWZkNGNkMDE2NGI4YjRhNzdjODdlMTc3OGZmZDcyZTBiZDY2MGUyOWEyYWE1NzgzMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y6CWD5MHeZj1fMwQXmRZsmjehPe9xWYJLSs26guWN4s) Do you know how to fix it?

Yes, you are right. I forgot to change line 434...
And I've solved the cuda problem in the new code, you can try it. (It seems that I didn't move the batch input to cuda properly, but it was stilling running well on my device (with input data on cpu and model on cuda). That's so weird...

**Comment by ZzZZCHS** [comment]
> Besides, I see when running the inference phrase, this python file [helper](https://github.com/Chat-3D/Chat-3D-v2/blob/main/utils/helper.py) is needed. But the _annotations_ you provided not contain these three files: ![image](https://private-user-images.githubusercontent.com/64463353/325907019-322ef4f6-bf50-4c1c-ae22-fee89740290d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjQ3NDcsIm5iZiI6MTcxNDEyNDQ0NywicGF0aCI6Ii82NDQ2MzM1My8zMjU5MDcwMTktMzIyZWY0ZjYtYmY1MC00YzFjLWFlMjItZmVlODk3NDAyOTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA5NDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMDU1ZjY4M2ZjNzQwYWI5YTA0MzdmYjRkZjE0YWY2NWVmMWNkNTM0YTQwMGM0OWY4NTgxYmZlYTVhNmY5MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lxFvaHD3OxuJBvaTLhp1nkA28OrAGWn86O_isLSJDq4) So I added the two files below `annotations/scannet/scannetv2-labels.combined.tsv` and `annotations/scanrefer/ScanRefer_filtered.json` from Scannet and Scanrefer to the _annotation_ directory, and I didn't find the file `annotations/scanrefer_unique_multiple_lookup.json` (it seems this file is not necessary). Is that right? Thanks again.

Yes. The code will automatically generate the `scanrefer_unique_multiple_lookup.json`. And thanks for your remind, I've uploaded the required files `scannetv2-labels.combined.tsv` and `ScanRefer_filtered.json` to Google Drive.

**Comment by ZzZZCHS** [comment]
> > Thanks for your reply and I have tried the newest code. But I got this error: ![aabe84017b1b4559e1b633c10138b8b](https://private-user-images.githubusercontent.com/64463353/325901711-a511559b-ac3d-4172-9016-8998708d0077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjQ3NDcsIm5iZiI6MTcxNDEyNDQ0NywicGF0aCI6Ii82NDQ2MzM1My8zMjU5MDE3MTEtYTUxMTU1OWItYWMzZC00MTcyLTkwMTYtODk5ODcwOGQwMDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA5NDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViOTVjYmIzNDg1MTUyMWMxNmY4Y2Y3YTY5M2RkNDkzYzhjM2U1NDdmNDNkY2QwMTg2NWQ1NWEwMGQxZmZkM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uspwxBwTI8O4tImbl1oRggcTQoBG45YY8tuYjONhcH0) So I change `evaluate all(model, val loaders, start epoch-1. alobal step, device, config)` to `evaluate_all(model, model_without_ddp, val_loaders, start_epoch - 1, global_step, device, config)`. But then I got this error: ![image](https://private-user-images.githubusercontent.com/64463353/325904000-95d74951-2944-4f6c-af2d-f896baf9e008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMjQ3NDcsIm5iZiI6MTcxNDEyNDQ0NywicGF0aCI6Ii82NDQ2MzM1My8zMjU5MDQwMDAtOTVkNzQ5NTEtMjk0NC00ZjZjLWFmMmQtZjg5NmJhZjllMDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA5NDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ODlkMGM0YTNhNmIwOWZkNGNkMDE2NGI4YjRhNzdjODdlMTc3OGZmZDcyZTBiZDY2MGUyOWEyYWE1NzgzMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y6CWD5MHeZj1fMwQXmRZsmjehPe9xWYJLSs26guWN4s) Do you know how to fix it?
> 
> Yes, you are right. I forgot to change line 434... And I've solved the cuda problem in the new code, you can try it. (It seems that I didn't move the batch input to cuda properly, but it was stilling running well on my device (with input data on cpu and model on cuda). That's so weird...

I find the reason: When the model is an instance of `DistributedDataParallel`, there is a wrapper before enterring the model's forward function, and it moves the batch input onto the right device [here](https://github.com/pytorch/pytorch/blob/main/torch/nn/parallel/distributed.py#L1518-L1524). So I didn't encounter the error when I was running in distributed setting...
