### ISSUE TITLE
Save test output

### ISSUE THREAD

**Issue by yitianlian** [Chat-3D/Chat-3D-v2#32]
How can I save the model's output from test pipline.

**Comment by ZzZZCHS** [comment]
The evaluating process would save the results under `outputs/`. You can find something like this:
<img width="279" alt="Screenshot 2024-05-04 at 10 30 21 AM" src="https://github.com/Chat-3D/Chat-3D-v2/assets/50910784/75a371fc-5b4d-49db-a887-499ffc10aa5c">
