### ISSUE TITLE
About the epoches in Training&Inference.

### ISSUE THREAD

**Issue by KaKa-101** [Chat-3D/Chat-3D-v2#34]
Hi, thanks for your great work. I have the following two questions:
1. Why do you set the `epochs=3` during training and inference? And do you suggest me to set it to a higher value(like 10, 20, etc) and will this help improve the LLM's performance in tasks like grounding, Q&A, etc?
2. Could you provide the code to visualize the b-box in the pictures?
Thanks a lot again.

**Comment by ZzZZCHS** [comment]
1. The `epochs` is only set for training. We didn't have much time or resources to test different epoch numbers. However, most recent MLLMs perform fine-tuning within one or two epochs, such as [LLaVA 1.5](https://github.com/haotian-liu/LLaVA/tree/main?tab=readme-ov-file#hyperparameters). So I guess a higher epoch value would not help a lot. Our practice is to set epoch number to 3 and early-stop at the second epoch. You can experiment with different epoch numbers to observe any differences. I'm also curious about this, so if you find anything noteworthy, please share it with us!
2. For visualization, you can refer to this [issue](https://github.com/Chat-3D/Chat-3D-v2/issues/12). And we use MeshLab to visualize the generated PLY files.

**Comment by KaKa-101** [comment]
Thanks for your reply. And I see you evaluated the model on Nr3D/Sr3D datasets (which are orginated from ReferIt3D benchmark) in your paper. But it seems that there isn't the part of Nr3D/Sr3D datasets in [preprocess](https://github.com/Chat-3D/Chat-3D-v2/tree/main/preprocess).

**Comment by ZzZZCHS** [comment]
We haven't evaluated the v2.1 model on Nr3D/Sr3D. We will add this in the future.

**Comment by KaKa-101** [comment]
Thanks. Looking forward to your release~
