### ISSUE TITLE
the relation module for v2.1 version

### ISSUE THREAD

**Issue by PanXiongAdam** [Chat-3D/Chat-3D-v2#35]
Hello, this is a interesting work.
I have a question for the relation module, which is not used in the v2.1 version. You are directly project the object into LLM  # line 14 for scripts/run.sh

**Comment by ZzZZCHS** [comment]
Yeah, the relation module doesn't help improve performance currently, so we disable it in v2.1. This means that the model has no access to the object positions in the 3D scene now. It is interesting that the model can still achieve good performance across these datasets, especially on ScanQA. We are still seeking a better solution to incorporate the position information of objects into the language model.

**Comment by PanXiongAdam** [comment]
@ZzZZCHS thank you for your response, it is a good work.
