### ISSUE TITLE
Details about incorporating Dinov2 features

### ISSUE THREAD

**Issue by WeitaiKang** [Chat-3D/Chat-3D-v2#39]
Hi authors,

I noticed that you have update a new model, Chat-Scene, featuring in incorporating Dinov2 features. Could you provide more details about its implementation?

For example, what is the interval of frame you use to sample 2d image? How do you aggregate Dinov2 features from different views?

**Comment by ZzZZCHS** [comment]
We followed the default setting in [openscene](https://github.com/pengsongyou/openscene/blob/main/scripts/preprocess/preprocess_2d_scannet.py#L30), where the sample frequency is 20.  

DINOv2 generates a 257×1024 feature vector for each image, consisting of a 1×1024 CLS feature and 256×1024 patch features, where each patch represents a 16×16 local region of the image. For each object mask within an image, we extract only the patch features that intersect with the mask. These extracted patch features are then averaged along the patch axis to produce a single 1×1024 feature vector per image. When considering patch features from multiple views, we compute a weighted average, with the weights based on the mask size in each image.

**Comment by WeitaiKang** [comment]
Great! Thanks for you clarification.
