### ISSUE TITLE
About trainned wights

### ISSUE THREAD

**Issue by Hank10032** [Chat-3D/Chat-3D-v2#4]
Your work is outstanding. I would like to ask when will the trained weights be made public?

**Comment by ZzZZCHS** [comment]
We've provided the [trained weight](https://drive.google.com/drive/folders/19wOjXYjca6w3JRVzbbFMgwiQj6kd6MXQ?usp=drive_link) for grounding task on ScanRefer. You can try it following the [inference guide](https://github.com/Chat-3D/Chat-3D-v2?tab=readme-ov-file#-training-and-inference).
