### ISSUE TITLE
Paper Release

### ISSUE THREAD

**Issue by yfcharm** [Chat-3D/Chat-3D-v2#40]
Great work!! I wonder if you have any plan to release technical paper? Could you please offer a timeline?

**Comment by ZzZZCHS** [comment]
Hello, thank you for your interest. The paper is scheduled for release by the end of this month.

**Comment by yfcharm** [comment]
Thanks for your reply. Looking forward to the latest release.

**Comment by ZzZZCHS** [comment]
Hi @yfcharm, we've released the [paper](https://arxiv.org/abs/2312.08168)~
