### ISSUE TITLE
Can't find sqa3d_test.json in inference process 

### ISSUE THREAD

**Issue by KarlCbw** [Chat-3D/Chat-3D-v2#41]
Hello!
I noticed something when I run the inference process, it shows that the sqa3d_test.json file is not in annotations folder. I have already download all prepared data in my workspace. Is it because this file hasn't been released?

**Comment by ZzZZCHS** [comment]
Hi, sorry for the inconvenience. The `sqa3d_test.json` has not beed released. You can change `sqa3d_test.json` [here](https://github.com/ZzZZCHS/Chat-Scene/blob/dev/scripts/config.py#L174) to `sqa3d_val.json` for evaluating on the validation set. (I've updated in the latest commit)
