### ISSUE TITLE
Question about Mask3D and 2D Multi-view Features

### ISSUE THREAD

**Issue by ghost** [Chat-3D/Chat-3D-v2#42]
Hi!
I have a couple of questions regarding the use of Mask3D and 2D feature extraction:
1. After using Mask3D for instance segmentation, do you use the Mask3D output (3D point cloud data) as input for the OpenScene 2D multi-view feature extraction process?
2. In the Chat-Scene code, there's a reference to seg_img_feat_file: annotations/scannet_mask3d_videofeats.pt. Is this file storing the 2D multi-view features extracted and fused for each object after Mask3D segmentation?

**Comment by ZzZZCHS** [comment]
Hi, thank you for your interest~
1. Yes. We use Mask3D's segmentation results (point cloud masks) as input for OpenScene, so that we can get the corresponding masks on 2D images.
2. Yes.

**Comment by ghost** [comment]
> Hi, thank you for your interest~
> 
> 1. Yes. We use Mask3D's segmentation results (point cloud masks) as input for OpenScene, so that we can get the corresponding masks on 2D images.
> 2. Yes.

Thank you so much for the quick response and clarification!
