### ISSUE TITLE
Question about the annotations

### ISSUE THREAD

**Issue by KaKa-101** [Chat-3D/Chat-3D-v2#43]
Thanks for your great work!
Could you provide the `gt_feat_file` and `gt_img_feat_file`?
![image](https://github.com/user-attachments/assets/1c97dc96-eda1-463b-97fb-35eebfe96855)
 Currently they are not provided in the [Google Drive](https://drive.google.com/drive/folders/1iwVFUkvveehvwGcAnJK3EwLxBt5ggR2c). Could you also explain how to get the `gt_feat_file` and `gt_img_feat_file`? I want to test the model's performance given the GT masks, should I change the following three files to GT files?
![image](https://github.com/user-attachments/assets/36092672-79a9-4283-b9d1-3ee1e88b76e2)
![image](https://github.com/user-attachments/assets/dde1fc20-4a68-47c6-aa92-3a9097a70f1d)
Thanks a lot for your kind help.

**Comment by QScloud-l** [comment]
Same issue. [Google Drive](https://drive.google.com/drive/folders/1iwVFUkvveehvwGcAnJK3EwLxBt5ggR2c) only contains 4 pt files. The file scannet_val_attributes.pt is required when I attempt to run the evaluation with the code provided in the README, but i don't know how to get it.

**Comment by ZzZZCHS** [comment]
> Thanks for your great work! Could you provide the `gt_feat_file` and `gt_img_feat_file`? ![image](https://private-user-images.githubusercontent.com/166525403/376864770-1c97dc96-eda1-463b-97fb-35eebfe96855.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODI0MzAsIm5iZiI6MTcyOTA4MjEzMCwicGF0aCI6Ii8xNjY1MjU0MDMvMzc2ODY0NzcwLTFjOTdkYzk2LWVkYTEtNDYzYi05N2ZiLTM1ZWViZmU5Njg1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxMjM1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2E5NjJhZjcyYzVjYTA0YTNkMTA3NjVjNGRjOTgwYjNiMzkwOTA5ODM1ODk5MWZmZWMyZjYyZjc4ZDFkNjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.a_nl7LEaifNLzGpIjrB85IWavAbZ8gOfSxREe-OXPB4) Currently they are not provided in the [Google Drive](https://drive.google.com/drive/folders/1iwVFUkvveehvwGcAnJK3EwLxBt5ggR2c). Could you also explain how to get the `gt_feat_file` and `gt_img_feat_file`? I want to test the model's performance given the GT masks, should I change the following three files to GT files? ![image](https://private-user-images.githubusercontent.com/166525403/376865207-36092672-79a9-4283-b9d1-3ee1e88b76e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODI0MzAsIm5iZiI6MTcyOTA4MjEzMCwicGF0aCI6Ii8xNjY1MjU0MDMvMzc2ODY1MjA3LTM2MDkyNjcyLTc5YTktNDI4My1iOWQxLTNlZTFlODhiNzZlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxMjM1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTQ2MTc1YmJkNGUyMDg5ZWU1ODdhZjRkYmUyMGRhMzliOWRiNTk1MWIxY2M5NWVjNTg2NWYwZDdjYzA3MDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.viX4g4x_sI7ksDGLfeDsaj1OSLnz5K-QbPg9wtGnZvg) ![image](https://private-user-images.githubusercontent.com/166525403/376865546-dde1fc20-4a68-47c6-aa92-3a9097a70f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODI0MzAsIm5iZiI6MTcyOTA4MjEzMCwicGF0aCI6Ii8xNjY1MjU0MDMvMzc2ODY1NTQ2LWRkZTFmYzIwLTRhNjgtNDdjNi1hYTkyLTNhOTA5N2E3MGYxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxMjM1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDg1MjEzMmNhZjY0YmY4YWE5NDZhMzM3NDU3Mzc5MzBlN2U2MjJiMGRkN2M5NjdlYTA3ZDMwNTc4M2QyMmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wiZSKDiUGKSLpmWvbuZybIt9tzBW2R-Xz2UImQpijwQ) Thanks a lot for your kind help.

@KaKa-101 Hi, I've uploaded GT feature files (`scannet_gt_uni3d_feats.pt` & `scannet_gt_videofeats.pt`) and GT attribute files (`scannet_train_attributes.pt` & `scannet_val_attributes.pt`) to the Google Drive. To get the GT feature files, you can also follow the [preprocess readme](https://github.com/ZzZZCHS/Chat-Scene/tree/dev/preprocess) but change the mask3d masks to the GT masks (which can be found in original ScanNet data).

If you want to test the model using GT masks, you also need to change the annotation files. The current annotation `scanrefer_mask3d_train.json` is based on mask3d segmented masks. You can create the GT annotation file by transforming the original scanrefer annotation `annotations/scanrefer/ScanRefer_filtered_train.json` to the same format as `scanrefer_mask3d_train.json`.

Besides, the model was trained with fixed number of objects (100) for each scene, while GT object numbers are varied for each scene (some of them are even larger than 100), this may lead to a low performance if you directly test the provided model with GT masks. I recommend training it with GT masks before the test. 

I'm not sure whether the current code is compatible with GT masks. Some code snippets may need slight modification (for example you need to change [this line](https://github.com/ZzZZCHS/Chat-Scene/blob/dev/dataset/base_dataset.py#L95) to `assigned_ids = torch.randperm(len(scene_locs))`). You can open a new issue if you meet any further problems.

**Comment by ZzZZCHS** [comment]
> Same issue. [Google Drive](https://drive.google.com/drive/folders/1iwVFUkvveehvwGcAnJK3EwLxBt5ggR2c) only contains 4 pt files. The file scannet_val_attributes.pt is required when I attempt to run the evaluation with the code provided in the README, but i don't know how to get it.

@QScloud-l Hi, I've uploaded `scannet_val_attributes.pt` to Google Drive. I forgot that this file is necessary for evaluation. Sorry for the inconvenience.

**Comment by QScloud-l** [comment]
> > Same issue. [Google Drive](https://drive.google.com/drive/folders/1iwVFUkvveehvwGcAnJK3EwLxBt5ggR2c) only contains 4 pt files. The file scannet_val_attributes.pt is required when I attempt to run the evaluation with the code provided in the README, but i don't know how to get it.
> 
> @QScloud-l Hi, I've uploaded `scannet_val_attributes.pt` to Google Drive. I forgot that this file is necessary for evaluation. Sorry for the inconvenience.

Thank you! In fact, I've found the way to generate the scannet_*_attributes.pt files within the preprocess directory. However, I've also found that scan2cap_val_corpus.json is also required for the scan2cap evaluation. I can't find a script to generate this file in the preprocess directory; I've only found some commented-out code. Could you please provide this file or the script? I greatly appreciate your kind assistance.

**Comment by ZzZZCHS** [comment]
@QScloud-l Thank you for pointing out the missing files. I've uploaded `scan2cap_val_corpus.json` just now. Check it~
