### ISSUE TITLE
Can't do evaluation in sqa3d benchmark

### ISSUE THREAD

**Issue by QScloud-l** [Chat-3D/Chat-3D-v2#44]
![image](https://github.com/user-attachments/assets/8e8830a5-6323-4ccb-ad94-886f389d51a8)
maybe this "==" should be "in"

**Comment by ZzZZCHS** [comment]
You are right. A mistake in a recent [commit](https://github.com/ZzZZCHS/Chat-Scene/commit/60ff87984188f5171273c9e5d20328a1340b2bbc#diff-c0514e5363a17b0dce324bfe26e7c1115bf7ce0a2dd47da67725895b303f287eR282)...
