### ISSUE TITLE
ScanNet test split point cloud feature

### ISSUE THREAD

**Issue by matthewdm0816** [Chat-3D/Chat-3D-v2#46]
Hi, thanks for your great work! From your README, I've noticed that ChatScene are also evaluated on benchmark (test) split of ScanRefer/Scan2Cap and ranked top on the leaderboard, can you also kindly provide this part of point cloud feature (since only train/val features are uploaded to Google Drive) to reproduce this result?

**Comment by ZzZZCHS** [comment]
Hi, I've uploaded some files for test set [here](https://drive.google.com/drive/folders/1iwVFUkvveehvwGcAnJK3EwLxBt5ggR2c):
<img width="1160" alt="Screenshot 2024-11-07 at 4 07 01 PM" src="https://github.com/user-attachments/assets/f2872f6c-48c7-4500-80a6-b95ea3980460">
Please let me know if I missed anything.

Besides, you can refer to the codes ([scanrefer](https://github.com/ZzZZCHS/Chat-Scene/blob/dev/others/process_scanrefer_test_results.py), [scan2cap](https://github.com/ZzZZCHS/Chat-Scene/blob/dev/others/process_scan2cap_test_results.py), [scanqa](https://github.com/ZzZZCHS/Chat-Scene/blob/dev/others/process_scanqa_test_results.py)) for processing predicted results on test sets.

**Comment by matthewdm0816** [comment]
Thank you for your quick response! 

Additionally I found a problem with your `scannet_mask3d_uni3d_feats.pt`, that some (training split) scene features (although rare) are missing. Is it intended (as they will be replaced by zero embeddings in code) or just they are indeed missing? 

E.g. {`scene0636_00`, `scene0154_00`} is missing from that file, which is required for ScanQA (train split)

**Comment by ZzZZCHS** [comment]
It seems that Mask3D skips these two scenes [here](https://github.com/JonasSchult/Mask3D/blob/11bd5ff94477ff7194e9a7c52e9fae54d73ac3b5/datasets/semseg.py#L638-L642). I hadn’t looked into this before.
