### ISSUE TITLE
DINOv2 features

### ISSUE THREAD

**Issue by wingrune** [Chat-3D/Chat-3D-v2#47]
Hello! Thank you for your great work! Could you specify, please, what version of pretrained DINOv2 model did you use? Are you planning to release the code for DINOv2 feature extraction on ScanNet?

**Comment by ZzZZCHS** [comment]
Hi, thank you for your interest! We used the pretrained [dinov2-large model](https://huggingface.co/facebook/dinov2-large). The code is still being organized, but we'll release it as soon as it’s ready. You can refer to [this issue](https://github.com/ZzZZCHS/Chat-Scene/issues/39) for some implementation details.

**Comment by wingrune** [comment]
Thank you for this clarification!
