### ISSUE TITLE
problem with running the run.sh script!!

### ISSUE THREAD

**Issue by samiulextreem** [Chat-3D/Chat-3D-v2#50]
trying to run run.sh throws error as below

`
srun: unrecognized option '--quotatype=reserved'
Try "srun --help" for more information
`
removing '--quotatype=reserved' option further creates problem as follows

`
srun: error: Invalid generic resource (gres) specification
`

I am confused if this code supposed to run in a local personal computer or in a cloud computer?

**Comment by Zeyad-Abdelreheem** [comment]
if you don't have a cluster of gpus you can comment that line.

**Comment by ZzZZCHS** [comment]
Hi @samiulextreem, thanks for your interest.

The `srun` [line](https://github.com/ZzZZCHS/Chat-Scene/blob/dev/scripts/run.sh#L56) is used for running code on GPU clusters managed by Slurm. If you are running on local environments, I recommend trying `torchrun` in this way:

replace [these two lines](https://github.com/ZzZZCHS/Chat-Scene/blob/dev/scripts/run.sh#L56-L57) with:
```
torchrun  --nnodes=1 --nproc_per_node=${gpu_num} \
          --rdzv_endpoint=${MASTER_ADDR}:${MASTER_PORT} \
          --rdzv_backend=c10d \
          tasks/train.py \
```

**Comment by samiulextreem** [comment]
> Hi @samiulextreem, thanks for your interest.
> 
> The `srun` [line](https://github.com/ZzZZCHS/Chat-Scene/blob/dev/scripts/run.sh#L56) is used for running code on GPU clusters managed by Slurm. If you are running on local environments, I recommend trying `torchrun` in this way:
> 
> replace [these two lines](https://github.com/ZzZZCHS/Chat-Scene/blob/dev/scripts/run.sh#L56-L57) with:
> 
> ```
> torchrun  --nnodes=1 --nproc_per_node=${gpu_num} \
>           --rdzv_endpoint=${MASTER_ADDR}:${MASTER_PORT} \
>           --rdzv_backend=c10d \
>           tasks/train.py \
> ```

greeting. I followied your instruction. But the following error appares.
`usage: train.py [-h] config_file [opts ...]`

Furthermore, i removed the whole 'srun' line and tried to run the code without cluster approach. But i got the following error 

`FileNotFoundError: [Errno 2] No such file or directory: 'annotations/scannet_mask3d_val_attributes.pt'
`
can you give me a solution of these?

**Comment by ZzZZCHS** [comment]
You need to follow the [preprocess](https://github.com/ZzZZCHS/Chat-Scene/tree/dev/preprocess#skip-the-data-preparation) instruction to download all necessary files and place them in the `annotations/` directory.

**Comment by samiulextreem** [comment]
greeting,


`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 11.75 GiB of which 46.19 MiB is free. Including non-PyTorch memory, this process has 11.36 GiB memory in use. Of the allocated memory 11.26 GiB is allocated by PyTorch, and 4.08 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
`

I am facing this problem. I have rtx3060 with 12 GB. can you inform how much memory is needed to interface with the model??

**Comment by ZzZZCHS** [comment]
The model was trained on four A100 with 80GB. For inference, a GPU with at least 24GB is needed.
