### ISSUE TITLE
Will the pretrained weight of 'objxx' task be released?

### ISSUE THREAD

**Issue by LilRedWu** [Chat-3D/Chat-3D-v2#6]
Thanks for your impressive and outstanding work!

Do you have any idea why the model outputs are Garbled characters (in pred) as described in the picture?

<img width="743" alt="screenshot" src="https://github.com/Chat-3D/Chat-3D-v2/assets/92014745/25cab7c9-61b8-4644-abfe-e43c3e3b50c2">

**Comment by ZzZZCHS** [comment]
These garbled characters may occur during the early steps of training. You may encounter the same error as described in this [issue](https://github.com/Chat-3D/Chat-3D-v2/issues/5#issuecomment-1898207892).

If you encounter any further problems, feel welcome to reopen the issue~

**Comment by LilRedWu** [comment]
Hi thanks for you reply. I've solved this problem!  And another thing is that, will the pretrained weight of obj alignment be released？ Because the pretrained model you've provied is fintuined on the grounding task, when I ask the model to explain the obj, the model only return the format of grounding task. Could you share the model weight of only 'objxx‘ task plz?  
![image](https://github.com/Chat-3D/Chat-3D-v2/assets/92014745/1205069e-7430-4b0e-8f2a-7c288097510e)

**Comment by LilRedWu** [comment]
> Thanks for your interest in our work. I've uploaded two more pretrained weights on [Google Drive](https://drive.google.com/drive/folders/1PoiWB53Yk3EQlrsilEMYHK9gpAF0q-0W?usp=drive_link). One is after the object alignment (`after_obj_align.pth`) and the other one is after the scene alignment (`after_scene_align.pth`). When you use `after_obj_align.pth`, remember to set `add_scene_token=False` in `run.sh`.
> 
> Actually these pretrained weights are also kind of overfitting to answer formats used in corresponding training data. We are still trying to reduce the overfitting problem and enhance the zero-shot ability.

Thank you so much!
