### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by kuaileqipaoshui** [Chat-3D/Chat-3D-v2#7]
Excuse me. I want to test the result, but how  to implement the evaluation on ScanQA validation set and on on Nr3D/Sr3D datasets? Looking forward to your reply!

**Comment by ZzZZCHS** [comment]
Thanks for your attention. I will update the evaluation details in the README soon. 
I can't do it right now because my rented server on AutoDL currently has no available GPUs. I need a GPU to validate the checkpoints and the evaluation process. Sorry for the inconvenience.

**Comment by kuaileqipaoshui** [comment]
> Thanks for your attention. I will update the evaluation details in the README soon. I can't do it right now because my rented server on AutoDL currently has no available GPUs. I need a GPU to validate the checkpoints and the evaluation process. Sorry for the inconvenience.

thanks very much! Hope to update soon, I can't wait to test it on the excellent checkpoint you provided!
