### ISSUE TITLE
Color of each instance

### ISSUE THREAD

**Issue by LilRedWu** [Chat-3D/Chat-3D-v2#9]
Hello! I'm currently prepare data from scratch. I've notice that the color for each instance is 3 * 4 tensor. Could you tell me how to prepare the color information like this? I tried the code in the [preprocess/scannetv2/precompute_instance_colors.py](https://github.com/cshizhe/vil3dref/blob/82a95d9e41ecd9920d678823eda1b366947da204/preprocess/scannetv2/precompute_instance_colors.py#L33), and end with the dictionary {['weight’](3*1),['means'](3*3)}.

**Comment by ZzZZCHS** [comment]
The 3 * 4 tensor is a concatenation of `weights` and `means`. 
For example, 
<img width="359" alt="Screenshot 2024-01-24 at 9 56 07 PM" src="https://github.com/Chat-3D/Chat-3D-v2/assets/50910784/f8b0a8e7-cac4-4f9a-9d5a-bd1ce7a45248">
is transformed from:
```
{
    weights = [0.3758, 0.3832, 0.2410],
    means = [[0.6205,  0.6655,  0.6347], [-0.0651,  0.0240,  0.0246], [-0.2847, -0.4738, -0.6316]]
}
```

**Comment by LilRedWu** [comment]
Thanks for you quick reply! Do you use the color for each instance  when inference using uni3d  or you just set it 0.4 as default?

**Comment by ZzZZCHS** [comment]
Just set it as default.

**Comment by ZzZZCHS** [comment]
Just set it as default.

**Comment by LilRedWu** [comment]
> Just set it as default.

Thank you! One last question! What version of Uni3D do you use?

**Comment by ZzZZCHS** [comment]
I think it was [Uni3d-g](https://huggingface.co/BAAI/Uni3D/blob/main/modelzoo/uni3d-g/model.pt).
